### ISSUE TITLE
Interest detection similar to Detectron2

### ISSUE THREAD

**Issue by DonaldTsang** [halcy/DeepDanbooruActivationMaps#3]
In detectron2 (see ![](https://user-images.githubusercontent.com/1381301/66535560-d3422200-eace-11e9-9123-5535d469db19.png)) you can breakdown an image based on what objects or parts or items are inside an image... is it possible to apply this to DDAM through image edge detection?

> having blurs between the wings and the shoulders in addition to the boobs
some of the pubes are showing, while a faux-penis has been blurred in the shady regions

**Comment by DonaldTsang** [comment]
Another concept: Recaptcha-like image regional refinement, for example present a 3x3 square of images for people to tag, where 5 of the images are not related to the tag in question, 3 of the images are human-affirmed images with the tag, and 1 single image where it is machine tagged to be true but not yet confirmed by a human (5-3-1 strategy).

In order to prevent bounding box bias in image orientation (+-45degrees) the images would have to be altered slightly such that people can tag them without the influence of background noise.
See: https://github.com/aleju/imgaug for possible aid in the system

Also in order to prevent overfitting and ML botting, "Adversarial Examples" would need to be implemented in order to fuzz things and make training better (in a reasonable manner that is not too extreme when compared distance in YCbCr or similar color system).
See: 
- https://github.com/tensorflow/cleverhans
- https://github.com/bethgelab/foolbox
- https://github.com/advboxes/AdvBox

**Comment by halcy** [comment]
It really isn't made for segmentation, so I'm not sure how one could effectively get super nice proper segment borders.

Wrt resistance to adversarial examples: This is a published model, so you're in a white-box situation - and as far as my understanding goes, that means you're fairly close to hosed no matter what - in which case it makes more sense to specifically look at where you'd want to use the model, what your expected threats are, and how to mitigate them other than by trying to make the model a tiny bit better (since you'll want those semi-automatic, non-ml mitigations anyways).

In any case, I see you did find the original authors repo, so I'll close this here - but feel free to fork off or copy my code if it's useful for your segmentation experiments.
